apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: analyzer-claim0
  name: analyzer-claim0
spec:
{{- if .Values.analyzer.persistence.storageClass }}
  storageClassName: {{ .Values.analyzer.persistence.storageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.analyzer.persistence.size }}
status: {}
