apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: analyzer
  name: analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: analyzer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app-network/upsource-net-name: 'true'
        app-service: analyzer
    spec:
      securityContext:
        runAsUser: 13001
        fsGroup: 13001
      containers:
        - name: analyzer
          image: {{ .Values.global.image.prefix }}{{ .Values.analyzer.image.repository }}:{{ .Values.analyzer.image.tag }}
          imagePullPolicy: {{ .Values.analyzer.image.pullPolicy | quote }}
          # command: ["tail", "-f", "/etc/hosts"]
          args:
            - --J-Xmx{{ .Values.global.env.UPSOURCE_ANALYZER_XMX }}
          env:
          {{- range $index, $topping := .Values.global.env }}
            {{- if $topping }}
            - name: {{ $index }}
              value: {{ $topping }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: 10061
            - containerPort: 8886
          resources: {}
          volumeMounts:
            - mountPath: /opt/upsource-analyzer/logs
              name: analyzer-claim0
      restartPolicy: Always
      volumes:
        - name: analyzer-claim0
          persistentVolumeClaim:
            claimName: analyzer-claim0
status: {}
