apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app-service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app-network/up-net: "true"
        app-service: cassandra
    spec:
      containers:
        - env:
            - name: UPSOURCE_SUBNET
            - name: constraint
              value: node==
          image: 'jetbrains/upsource-cassandra:'
          name: cassandra
          ports:
            - containerPort: 9042
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: cassandra-claim0
      restartPolicy: Always
      volumes:
        - name: cassandra-claim0
          persistentVolumeClaim:
            claimName: cassandra-claim0
status: {}
