apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/up-net: "true"
        io.kompose.service: cassandra
    spec:
      containers:
        - env:
            - name: UPSOURCE_SUBNET
            - name: constraint
              value: node==
          image: 'jetbrains/upsource-cassandra:'
          name: cassandra
          ports:
            - containerPort: 9042
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: cassandra-claim0
      restartPolicy: Always
      volumes:
        - name: cassandra-claim0
          persistentVolumeClaim:
            claimName: cassandra-claim0
status: {}
