apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app-service: cassandra
  name: cassandra
spec:
  type: {{ .Values.cassandra.service.type }}
  ports:
    - name: {{ .Values.cassandra.service.port | quote }}
      port: {{ .Values.cassandra.service.port }}
      targetPort: {{ .Values.cassandra.service.port }}
  selector:
    app-service: cassandra
