apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: cassandra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app-network/upsource-net-name: "true"
        app-service: cassandra
    spec:
      containers:
        - env:
          image: {{ .Values.global.image.prefix }}{{ .Values.cassandra.image.repository }}:{{ .Values.global.image.UPSOURCE_VERSION }}
          imagePullPolicy: {{ .Values.cassandra.image.pullPolicy | quote }}
          name: cassandra
          ports:
            - containerPort: 9042
          resources: {}
          volumeMounts:
            - name: cassandra-claim0
              mountPath: /var/lib/cassandra
{{ include "configmap.volumeMounts.log4j.xml" . | indent 12 }}
      restartPolicy: Always
      volumes:
        - name: cassandra-claim0
          persistentVolumeClaim:
            claimName: cassandra-claim0
{{ include "configmap.volume.log4j.xml" . | indent 8 }}
