apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: cassandra-claim0
  name: cassandra-claim0
spec:
{{- if .Values.cassandra.persistence.storageClass }}
  storageClassName: {{ .Values.cassandra.persistence.storageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cassandra.persistence.size }}
status: {}
