apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: cluster-init-claim0
  name: cluster-init-claim0
spec:
{{- if .Values.clusterInit.persistence.storageClass }}
  storageClassName: {{ .Values.clusterInit.persistence.storageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clusterInit.persistence.size }}
