apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-service: cluster-init
  name: cluster-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: cluster-init
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/clusterconfig202011956-up-net: "true"
        app-service: cluster-init
    spec:
      containers:
        - args:
            - --J{{ .Values.clusterInit.args.UPSOURCE_CLUSTER_INIT_XMX }}
          env:
          {{- range $index, $topping := .Values.global.env }}
            {{- if $topping }}
            - name: {{ $index }}
              value: {{ $topping | quote }}
            {{- end }}
          {{- end }}
          image: {{ .Values.global.image.prefix }}{{ .Values.clusterInit.image.repository }}:{{ .Values.global.image.UPSOURCE_VERSION }}
          imagePullPolicy: {{ .Values.clusterInit.image.pullPolicy | quote }}
          name: cluster-init
          # command:
          #   - tail
          #   - -f
          #   - /etc/hosts
          ports:
            - containerPort: 10061
            - containerPort: 8886
          resources: {}
          volumeMounts:
            - name: cluster-init-claim0
              mountPath: /opt/upsource-cluster-init/logs
{{ include "configmap.volumeMounts.log4j.xml" . | indent 12 }}
      restartPolicy: Always
      securityContext:
        runAsUser: 13001
        fsGroup: 13001
      volumes:
        - name: cluster-init-claim0
          persistentVolumeClaim:
            claimName: cluster-init-claim0
{{ include "configmap.volume.log4j.xml" . | indent 8 }}
