apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: file-clustering
  name: file-clustering
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: file-clustering
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app-network/upsource-net-name: "true"
        app-service: file-clustering
    spec:
      containers:
        - args:
            - --J{{ .Values.fileClustering.args.UPSOURCE_FILE_CLUSTERING_XMX }}
          env:
          {{- range $index, $topping := .Values.global.env }}
            {{- if $topping }}
            - name: {{ $index }}
              value: {{ $topping | quote }}
            {{- end }}
          {{- end }}
          image: {{ .Values.global.image.prefix }}{{ .Values.fileClustering.image.repository }}:{{ .Values.global.image.UPSOURCE_VERSION }}
          imagePullPolicy: {{ .Values.fileClustering.image.pullPolicy | quote }}
          name: file-clustering
          ports:
            - containerPort: 10061
            - containerPort: 8886
          resources: {}
          volumeMounts:
            - name: file-clustering-claim0
              mountPath: /opt/upsource-file-clustering/logs
{{ include "configmap.volumeMounts.log4j.xml" . | indent 12 }}
      restartPolicy: Always
      securityContext:
        runAsUser: 13001
        fsGroup: 13001
      volumes:
        - name: file-clustering-claim0
          persistentVolumeClaim:
            claimName: file-clustering-claim0
{{ include "configmap.volume.log4j.xml" . | indent 8 }}
