apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: file-clustering
  name: file-clustering
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: file-clustering
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app-network/upsource-net-name: "true"
        app-service: file-clustering
    spec:
      containers:
        - args:
            - --Jupsource_file_clustering_xmx
          env:
            - name: UPSOURCE_SUBNET
              value: upsource_subnet
            - name: CASSANDRA_HOSTS
              value: cassandra
            - name: CASSANDRA_NATIVE_TRANSPORT_PORT
              value: "9042"
            - name: HUB_KEYSTORE_PASSWORD
              value: hub_keystore_password
            - name: HUB_KEYSTORE_PATH
              value: hub_keystore_path
            - name: HUB_URL
              value: hub_url
            - name: UPSOURCE_ANALYZER_XMX
              value: upsource_analyzer_xmx
            - name: UPSOURCE_BACKUPS_PATH_ON_HOST_SYSTEM
              value: upsource_backups_path_on_host_system
            - name: UPSOURCE_DATABASE
              value: datastax
            - name: UPSOURCE_FILE_CLUSTERING_XMX
              value: upsource_file_clustering_xmx
            - name: UPSOURCE_FRONTEND_XMX
              value: upsource_frontend_xmx
            - name: UPSOURCE_IMAGES_PREFIX
              value: upsource_images_prefix
            - name: UPSOURCE_MONITORING_LISTEN_PORT
              value: upsource_monitoring_listen_port
            - name: UPSOURCE_NET_NAME
              value: upsource_net_name
            - name: UPSOURCE_OPSCENTER_XMX
              value: upsource_opscenter_xmx
            - name: UPSOURCE_PSI_AGENT_XMX
              value: upsource_psi_agent_xmx
            - name: UPSOURCE_PSI_BROKER_LISTEN_PORT
              value: upsource_psi_broker_listen_port
            - name: UPSOURCE_PSI_BROKER_XMX
              value: upsource_psi_broker_xmx
            - name: UPSOURCE_SERVICE_ID
              value: upsource_service_id
            - name: UPSOURCE_SERVICE_LISTEN_ADDRESS
              value: 0.0.0.0
            - name: UPSOURCE_SERVICE_MESSAGING_PORT
              value: "10061"
            - name: UPSOURCE_SERVICE_SECRET
              value: upsource_service_secret
            - name: UPSOURCE_STATISTICS_UPLOAD
              value: "true"
            - name: UPSOURCE_SUBNET
              value: upsource_subnet
            - name: UPSOURCE_URL
              value: upsource_url
            - name: UPSOURCE_VERSION
              value: upsource_version
          image: upsource_images_prefixjetbrains/upsource-file-clustering:upsource_version
          name: file-clustering
          ports:
            - containerPort: 10061
            - containerPort: 8886
          resources: {}
          volumeMounts:
            - mountPath: /opt/upsource-file-clustering/logs
              name: file-clustering-claim0
      restartPolicy: Always
      volumes:
        - name: file-clustering-claim0
          persistentVolumeClaim:
            claimName: file-clustering-claim0
status: {}
