apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app-service: file-clustering
  name: file-clustering
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: file-clustering
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app-network/up-net: "true"
        app-service: file-clustering
    spec:
      containers:
        - args:
            - --J
          env:
            - name: CASSANDRA_HOSTS
              value: cassandra
            - name: CASSANDRA_NATIVE_TRANSPORT_PORT
              value: "9042"
            - name: UPSOURCE_DATABASE
              value: datastax
            - name: UPSOURCE_SERVICE_LISTEN_ADDRESS
              value: 0.0.0.0
            - name: UPSOURCE_SERVICE_MESSAGING_PORT
              value: "10061"
            - name: UPSOURCE_STATISTICS_UPLOAD
              value: "true"
            - name: UPSOURCE_SUBNET
          image: 'jetbrains/upsource-file-clustering:'
          name: file-clustering
          ports:
            - containerPort: 10061
            - containerPort: 8886
          resources: {}
          volumeMounts:
            - mountPath: /opt/upsource-file-clustering/logs
              name: file-clustering-claim0
      restartPolicy: Always
      volumes:
        - name: file-clustering-claim0
          persistentVolumeClaim:
            claimName: file-clustering-claim0
status: {}
