apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: file-clustering-claim0
  name: file-clustering-claim0
spec:
{{- if .Values.fileClustering.persistence.storageClass }}
  storageClassName: {{ .Values.fileClustering.persistence.storageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.fileClustering.persistence.size }}
