apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: frontend-claim0
  name: frontend-claim0
spec:
{{- if .Values.frontend.persistence.storageClass }}
  storageClassName: {{ .Values.frontend.persistence.storageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.frontend.persistence.size }}
status: {}
