apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app-network/upsource-net-name: "true"
        app-service: frontend
    spec:
      containers:
        - args:
            - --J-Xmx{{ .Values.global.env.UPSOURCE_FRONTEND_XMX }}
          env:
          {{- range $index, $topping := .Values.global.env }}
            {{- if $topping }}
            - name: {{ $index }}
              value: {{ $topping | quote }}
            {{- end }}
          {{- end }}
          image: {{ .Values.global.image.prefix }}{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | quote }}
          name: frontend
          ports:
            - containerPort: 10061
            - containerPort: 8886
            - containerPort: 10070
          resources: {}
          volumeMounts:
            - name: frontend-claim0
              mountPath: /opt/upsource-frontend/logs
      restartPolicy: Always
      securityContext:
        runAsUser: 13001
        fsGroup: 13001
      volumes:
        - name: frontend-claim0
          persistentVolumeClaim:
            claimName: frontend-claim0
status: {}
