apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: frontend
  name: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app-service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app-service: frontend
    spec:
      containers:
        - args:
            - --J{{ .Values.frontend.args.UPSOURCE_FRONTEND_XMX }}
          env:
{{- include "upsource.global.envirments" . | indent 10 }}
          image: {{ .Values.global.image.prefix }}{{ .Values.frontend.image.repository }}:{{ .Values.global.image.UPSOURCE_VERSION }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | quote }}
          name: frontend
          ports:
            - containerPort: 10061
            - containerPort: 8886
            - containerPort: {{ .Values.frontend.service.port }}
          resources: {}
          volumeMounts:
            - name: frontend-claim0
              mountPath: /opt/upsource-frontend/logs
{{ include "configmap.volumeMounts.log4j.xml" . | indent 12 }}
      restartPolicy: Always
      securityContext:
        runAsUser: 13001
        fsGroup: 13001
      volumes:
        - name: frontend-claim0
          persistentVolumeClaim:
            claimName: frontend-claim0
{{ include "configmap.volume.log4j.xml" . | indent 8 }}
