apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app-service: frontend
  name: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: "10061"
      port: 10061
      targetPort: 10061
    - name: "8886"
      port: 8886
      targetPort: 8886
    - name: {{ .Values.frontend.service.port | quote }}
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    app-service: frontend
