apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: frontend-claim0
  name: frontend-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.frontend.persistence.size }}
status: {}
