apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app-service: haproxy
  name: haproxy
spec:
  ports:
    - name: {{ .Values.haproxy.service.port | quote }}
      port: {{ .Values.haproxy.service.port }}
      targetPort: {{ .Values.haproxy.service.port }}
  selector:
    app-service: haproxy
