apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: haproxy
  strategy: {}
  template:
    metadata:
      annotations:
      labels:
        app-network/upsource-net-name: "true"
        app-service: haproxy
    spec:
      containers:
        - env:
            - name: MONITORING_HOST
              value: monitoring
            - name: MONITORING_PORT
              value: upsource_monitoring_listen_port
            - name: UPSOURCE_EXPOSED_PROXY_PORT
              value: "8080"
            - name: UPSOURCE_MONITORING_LISTEN_PORT
              value: upsource_monitoring_listen_port
            - name: UPSOURCE_SUBNET
              value: upsource_subnet
            - name: constraint
              value: node==upsource_proxy_node
          image: upsource_images_prefixjetbrains/upsource-proxy:upsource_version
          name: haproxy
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
