apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app-service: haproxy
  name: haproxy
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app-service: haproxy
status:
  loadBalancer: {}
