apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: haproxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/up-net: "true"
        io.kompose.service: haproxy
    spec:
      containers:
        - env:
            - name: MONITORING_HOST
              value: monitoring
            - name: MONITORING_PORT
            - name: UPSOURCE_EXPOSED_PROXY_PORT
              value: "8080"
            - name: UPSOURCE_MONITORING_LISTEN_PORT
            - name: UPSOURCE_SUBNET
            - name: constraint
              value: node==
          image: 'jetbrains/upsource-proxy:'
          name: haproxy
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
