apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app-service: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: haproxy
  strategy: {}
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app-network/up-net: "true"
        app-service: haproxy
    spec:
      containers:
        - env:
            - name: MONITORING_HOST
              value: monitoring
            - name: MONITORING_PORT
            - name: UPSOURCE_EXPOSED_PROXY_PORT
              value: "8080"
            - name: UPSOURCE_MONITORING_LISTEN_PORT
            - name: UPSOURCE_SUBNET
            - name: constraint
              value: node==
          image: 'jetbrains/upsource-proxy:'
          name: haproxy
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
