apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: haproxy
  strategy: {}
  template:
    metadata:
      annotations:
      labels:
        app-network/upsource-net-name: "true"
        app-service: haproxy
    spec:
      containers:
        - env:
            - name: MONITORING_HOST
              value: "opscenter.default.svc.cluster.local"
            - name: MONITORING_PORT
              value: {{ .Values.global.env.UPSOURCE_MONITORING_LISTEN_PORT | quote }}
            - name: UPSOURCE_EXPOSED_PROXY_PORT
              value: "8080"
            - name: UPSOURCE_MONITORING_LISTEN_PORT
              value: {{ .Values.global.env.UPSOURCE_MONITORING_LISTEN_PORT | quote }}
          image: {{ .Values.global.image.prefix }}{{ .Values.haproxy.image.repository }}:{{ .Values.global.image.UPSOURCE_VERSION }}
          imagePullPolicy: {{ .Values.haproxy.image.pullPolicy | quote }}
          name: haproxy
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
