apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app-service: hub
  name: hub
spec:
  type: {{ .Values.hub.service.type }}
  ports:
    - name: {{ .Values.hub.service.port | quote }}
      port: {{ .Values.hub.service.port }}
      targetPort: {{ .Values.hub.service.port }}
  selector:
    app-service: hub
status:
  loadBalancer: {}
