apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: opscenter
  name: opscenter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opscenter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/up-net: "true"
        io.kompose.service: opscenter
    spec:
      containers:
        - args:
            - --J
          env:
            - name: CASSANDRA_HOSTS
              value: cassandra
            - name: CASSANDRA_NATIVE_TRANSPORT_PORT
              value: "9042"
            - name: UPSOURCE_DATABASE
              value: datastax
            - name: UPSOURCE_SERVICE_LISTEN_ADDRESS
              value: 0.0.0.0
            - name: UPSOURCE_SERVICE_MESSAGING_PORT
              value: "10061"
            - name: UPSOURCE_STATISTICS_UPLOAD
              value: "true"
            - name: UPSOURCE_SUBNET
            - name: UPSOURCE_WEB_SERVER_LISTEN_PORT
            - name: constraint
              value: node==
          image: 'jetbrains/upsource-opscenter:'
          name: opscenter
          ports:
            - containerPort: 10061
            - containerPort: 8886
            - containerPort: 0
          resources: {}
          volumeMounts:
            - mountPath: /opt/upsource-opscenter/logs
              name: opscenter-claim0
            - mountPath: /opt/upsource-opscenter/backup
              name: opscenter-claim1
      restartPolicy: Always
      volumes:
        - name: opscenter-claim0
          persistentVolumeClaim:
            claimName: opscenter-claim0
        - name: opscenter-claim1
          persistentVolumeClaim:
            claimName: opscenter-claim1
status: {}
