apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app-service: opscenter
  name: opscenter
spec:
  type: {{ .Values.opsCenter.service.type }}
  ports:
    - name: "10061"
      port: 10061
      targetPort: 10061
    - name: "8886"
      port: 8886
      targetPort: 8886
    - name: "0"
      port: 0
      targetPort: 0
  selector:
    app-service: opscenter
status:
  loadBalancer: {}
