apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: opscenter-claim1
  name: opscenter-claim1
spec:
{{- if .Values.opsCenter.persistence.storageClass }}
  storageClassName: {{ .Values.opsCenter.persistence.storageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
