apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: opscenter-claim0
  name: opscenter-claim0
spec:
{{- if .Values.opsCenter.persistence.storageClass }}
  storageClassName: {{ .Values.opsCenter.persistence.storageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.opsCenter.persistence.size }}
