apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: opscenter
  name: opscenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: opscenter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app-network/upsource-net-name: "true"
        app-service: opscenter
    spec:
      containers:
        - args:
            - --J{{ .Values.opsCenter.args.UPSOURCE_OPSCENTER_XMX }}
          env:
          {{- range $index, $topping := .Values.global.env }}
            {{- if $topping }}
            - name: {{ $index }}
              value: {{ $topping | quote }}
            {{- end }}
          {{- end }}
          image: {{ .Values.global.image.prefix }}{{ .Values.opsCenter.image.repository }}:{{ .Values.opsCenter.image.tag }}
          imagePullPolicy: {{ .Values.opsCenter.image.pullPolicy | quote }}
          name: opscenter
          ports:
            - containerPort: 10061
            - containerPort: 8886
            - containerPort: {{ .Values.global.env.UPSOURCE_MONITORING_LISTEN_PORT }}
          resources: {}
          volumeMounts:
            - name: opscenter-claim0
              mountPath: /opt/upsource-opscenter/logs
              subPath: logs
            - name: opscenter-claim0
              mountPath: /opt/upsource-opscenter/backup
              subPath: backup
{{ include "configmap.volumeMounts.log4j.xml" . | indent 12 }}
      restartPolicy: Always
      securityContext:
        runAsUser: 13001
        fsGroup: 13001
      volumes:
        - name: opscenter-claim0
          persistentVolumeClaim:
            claimName: opscenter-claim0
{{ include "configmap.volume.log4j.xml" . | indent 8 }}
