apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: psi-broker
  name: psi-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: psi-broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app-network/upsource-net-name: "true"
        app-service: psi-broker
    spec:
      containers:
        - args:
            - --J{{ .Values.psiBroker.args.UPSOURCE_PSI_BROKER_XMX }}
          env:
          {{- range $index, $topping := .Values.global.env }}
            {{- if $topping }}
            - name: {{ $index }}
              value: {{ $topping | quote }}
            {{- end }}
          {{- end }}
          image: {{ .Values.global.image.prefix }}{{ .Values.psiBroker.image.repository }}:{{ .Values.psiBroker.image.tag }}
          imagePullPolicy: {{ .Values.psiBroker.image.pullPolicy | quote }}
          name: psi-broker
          ports:
            - containerPort: 10061
            - containerPort: 8886
            - containerPort: {{ .Values.global.env.UPSOURCE_PSI_BROKER_LISTEN_PORT }}
          resources: {}
          volumeMounts:
            - name: psi-broker-claim0
              mountPath: /opt/upsource-psi-broker/logs
{{ include "configmap.volumeMounts.log4j.xml" . | indent 12 }}
      restartPolicy: Always
      securityContext:
        runAsUser: 13001
        fsGroup: 13001
      volumes:
        - name: psi-broker-claim0
          persistentVolumeClaim:
            claimName: psi-broker-claim0
{{ include "configmap.volume.log4j.xml" . | indent 8 }}
