apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: psi-agent-claim0
  name: psi-agent-claim0
spec:
{{- if .Values.psiAgent.persistence.storageClass }}
  storageClassName: {{ .Values.psiAgent.persistence.storageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.psiAgent.persistence.size }}
status: {}
