apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app-service: psi-broker
  name: psi-broker
spec:
  type: {{ .Values.psiBroker.service.type }}
  ports:
    - name: "10061"
      port: 10061
      targetPort: 10061
    - name: "8886"
      port: 8886
      targetPort: 8886
    - name: {{ .Values.psiBroker.service.port | quote }}
      port: {{ .Values.psiBroker.service.port }}
      targetPort: {{ .Values.psiBroker.service.port }}
  selector:
    app-service: psi-broker
