apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app-service: psi-agent
  name: psi-agent
spec:
  type: ClusterIP
  ports:
    - name: "10061"
      port: 10061
      targetPort: 10061
    - name: "8886"
      port: 8886
      targetPort: 8886
  selector:
    app-service: psi-agent
