apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app-service: psi-agent
  name: psi-agent
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app-service: psi-agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        app-network/upsource-net-name: "true"
        app-service: psi-agent
    spec:
      containers:
        - args:
            - --J{{ .Values.psiAgent.args.UPSOURCE_PSI_AGENT_XMX }}
          env:
            - name: UPSOURCE_PSI_BROKER_HOST
              value: "psi-broker.default.svc.cluster.local"
          {{- range $index, $topping := .Values.global.env }}
            {{- if $topping }}
            - name: {{ $index }}
              value: {{ $topping | quote }}
            {{- end }}
          {{- end }}
          image: {{ .Values.global.image.prefix }}{{ .Values.psiAgent.image.repository }}:{{ .Values.psiAgent.image.tag }}
          imagePullPolicy: {{ .Values.psiAgent.image.pullPolicy | quote }}
          name: psi-agent
          ports:
            - containerPort: 10061
            - containerPort: 8886
          resources: {}
          volumeMounts:
            - name: psi-agent-claim0
              mountPath: /opt/upsource-psi-agent/logs
{{ include "configmap.volumeMounts.log4j.xml" . | indent 12 }}
      restartPolicy: Always
      securityContext:
        runAsUser: 13001
        fsGroup: 13001
      volumes:
        - name: psi-agent-claim0
          persistentVolumeClaim:
            claimName: psi-agent-claim0
{{ include "configmap.volume.log4j.xml" . | indent 8 }}
