apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: psi-broker-claim0
  name: psi-broker-claim0
spec:
{{- if .Values.psiBroker.persistence.storageClass }}
  storageClassName: {{ .Values.psiBroker.persistence.storageClass }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.psiBroker.persistence.size }}
