apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: psi-broker
  name: psi-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: psi-broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/up-net: "true"
        io.kompose.service: psi-broker
    spec:
      containers:
        - args:
            - --J
          env:
            - name: CASSANDRA_HOSTS
              value: cassandra
            - name: CASSANDRA_NATIVE_TRANSPORT_PORT
              value: "9042"
            - name: UPSOURCE_DATABASE
              value: datastax
            - name: UPSOURCE_PSI_BROKER_LISTEN_PORT
            - name: UPSOURCE_SERVICE_LISTEN_ADDRESS
              value: 0.0.0.0
            - name: UPSOURCE_SERVICE_MESSAGING_PORT
              value: "10061"
            - name: UPSOURCE_STATISTICS_UPLOAD
              value: "true"
            - name: UPSOURCE_SUBNET
          image: 'jetbrains/upsource-psi-broker:'
          name: psi-broker
          ports:
            - containerPort: 10061
            - containerPort: 8886
            - containerPort: 0
          resources: {}
          volumeMounts:
            - mountPath: /opt/upsource-psi-broker/logs
              name: psi-broker-claim0
      restartPolicy: Always
      volumes:
        - name: psi-broker-claim0
          persistentVolumeClaim:
            claimName: psi-broker-claim0
status: {}
