apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-service: upsource-backups-path-on-host-system
  name: upsource-backups-path-on-host-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
